#!/usr/bin/env node
var command = require('commander')
            .version('0.1.0')
            .option('-p, --port [port]', 'Port for server to run on (default 8080)')
            .option('-d, --dir [path]', 'Shared directory (default current working directory)')
            .parse(process.argv),

    port = command.port || 8080,
    path = command.dir || process.cwd(),
    server = require('./index')(port, path);
